redirect_url = "/submit-your-ers-annual-return?aoRef=123PA12345678&taxYear=2014%2F15&ersSchemeRef=XA1100000000000&schemeType=CSOP&schemeName=MyScheme&hmac=qlQmNGgreJRqJroWUUu0MxLq2oo%3D"
credential_strength = "Strong"
confidence_level = "50"
affinity_group = "Organisation"
enrolement.key = "IR-PAYE"
enrolement.identifier0.name = "TaxOfficeNumber"
enrolement.identifier1.name = "TaxOfficeReference"
enrolement.identifier0.value = "1234"
enrolement.identifier1.value = "GA4567"
